# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
    monitor: 'Hospitals'

# Rules config 
rule_files:
  - "rules/NhiDongThanhPho.yml"
  - "rules/phongkham40.yml"
  - "rules/benhviene.yml"
  - "rules/benhvienquany110.yml"
  - "rules/benhvienthanhhoa.yml"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['10.0.0.13:9093']
    basic_auth:
      username: admin
      password: vietnam@1234

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'Nhi-Dong-Thanh-Pho'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Nhi Đồng Thành Phố
          - 10.0.2.38:9100
          - 10.0.2.40:9100
          - 10.0.2.41:9100
          - 10.0.2.42:9100
          - 10.0.2.43:9100

  - job_name: 'Phong-Kham-40'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Phòng Khám 40
          - 192.168.10.230:19100
          - 192.168.10.231:9100
          - 192.168.10.234:19100
          - 192.168.10.235:9100

  - job_name: 'Benh-Vien-E'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện E
          - '192.168.0.238:9100'
          - '192.168.0.245:9100'
          - '192.168.0.244:9100'
          - '192.168.0.247:9100'
          - '192.168.0.242:9100'
          - '192.168.0.250:9100'
          - '192.168.0.251:9100'

  - job_name: 'Benh-Vien-110'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện QY 110
          - '10.110.55.11:9100'
          - '10.110.115.112:9100'
          - '10.110.115.89:9100'
          - '10.110.102.67:9100'
          - '10.110.115.110:9100'
          - '10.110.102.113:9100'
          - '10.110.102.88:9100'
          - '10.110.102.109:9100'

  - job_name: 'Benh-Vien-DK-ThanhHoa'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện Đa Khoa Thanh Hóa
          - '192.168.18.152:9100'
          - '192.168.18.153:9100'
          - '192.168.18.154:9100'
          - '192.168.18.155:9100'
          - '192.168.18.156:9100'
          - '192.168.18.157:9100'
          - '192.168.18.158:9100'
          - '192.168.18.160:9100'
          - '192.168.18.199:9100'
          - '192.168.18.200:9100'
          - '192.168.18.202:9100'
          - '192.168.18.203:9100'
          - '192.168.18.210:9100'
