# my global config
global:
  scrape_interval:     1s 
  evaluation_interval: 1s 

  external_labels:
    monitor: 'Hospitals-Container'

rule_files:
  - './rules/dhy/*.yml'
  - './rules/pk40/*.yml'
  - './rules/ivirse/103.9.211.120.yml'
  - './rules/ivirse/103.9.211.87.yml'
  - './rules/isofh-local/10.0.0.55.yml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['10.0.0.14:9093']
    basic_auth:
      username: admin
      password: toivaban

scrape_configs:
  - job_name: 'ivirse'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - '103.9.211.120:19092'
        - '103.9.211.120:9092'
        - '103.9.211.87:19094'
        - '103.9.211.87:19093'

  - job_name: 'dhy'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - '192.168.55.162:19092'
        - '192.168.55.162:9099'


  - job_name: 'pk40'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - '192.168.10.230:19092'
        - '192.168.10.231:19092'
        - '192.168.10.234:19092'
        - '192.168.10.235:19092'
        - '192.168.10.230:9092'
        - '192.168.10.231:9092'
        - '192.168.10.234:19093'
        - '192.168.10.235:19093'

  - job_name: 'isofhlocal'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - '10.0.0.55:19092'
        - '10.0.0.55:19093'