# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
    monitor: 'Hospitals'

rule_files:
  # - 'rules/BachMaiRules.yml'
  # - "rules/MediplusRules.yml"
  - "rules/NhiDongThanhPho.yml"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['10.0.0.13:9093']
    basic_auth:
      username: admin
      password: vietnam@1234

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'Nhi-Dong-Thanh-Pho'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Nhi Đồng Thành Phố
          - 10.0.2.38:9100
          - 10.0.2.40:9100
          - 10.0.2.41:9100
          - 10.0.2.42:9100
          - 10.0.2.43:9100
  - job_name: 'Phong-Kham-40'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Phòng Khám 40
          - 192.168.10.230:19100
