global:
  resolve_timeout: 1m

receivers:
- name: System-Team
  webhook_configs:
  - url: 'http://10.0.0.13:9087/alert/-815609975'

- name: BV-BachMai-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-932865047'


- name: Mediplus-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'

- name: jenkins-tuan-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'

route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 10s
  repeat_interval: 1m
  receiver: System-Team
  routes:
   - include: './alertmanager/include/*.yml'



