global:
  resolve_timeout: 1m

receivers:
- name: nhidongthanhpho-telegram
  webhook_configs:
  - url: 'http://10.0.0.13:9087/alert/-901133248'

- name: systems-team-telegram
  webhook_configs:
  - url: 'http://10.0.0.13:9087/alert/-815609975'


route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 10s
  repeat_interval: 1m
  receiver: systems-team-telegram
  routes:
# RAM 
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38:9100
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 2s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.40:9100
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 2s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.41:9100
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 2s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.42:9100
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 2s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.43:9100
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 2s   
   
# CPU
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38:9100
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.40:9100
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.41:9100
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.42:9100
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.43:9100
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s





# DISK
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38:9100
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.40:9100
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.41:9100
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.42:9100
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.43:9100
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s

