global:
  resolve_timeout: 1m

receivers:
- name: nhidongthanhpho-telegram
  webhook_configs:
  - url: 'http://10.0.0.13:9087/alert/-932865047'

route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 10s
  repeat_interval: 1m
  receiver: nhidongthanhpho-telegram
  routes:
# RAM 
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 2s
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.0.210:9100
        category: memory  
      receiver: nhidongthanhpho-telegram
      group_wait: 4s
# CPU
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.0.211:19100
        category: cpu  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s
# DISK
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.0.211:19100
        category: disk  
      receiver: nhidongthanhpho-telegram
      group_wait: 1s
