global:
  resolve_timeout: 1m

receivers:
- name: tuan-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9088/alert/-999710731'

route:
  continue: false
  group_by: ['instance']
  group_interval: 30s
  group_wait: 10s
  repeat_interval: 1m
  receiver: tuan-telegram
  routes:
# RAM 
    - match:
        app_type: Demo
        instance: 10.0.0.55:11092
        category: container 
        list_service: {{ $labels.name }} 
      receiver: tuan-telegram
      group_wait: 2s

