global:
  resolve_timeout: 1m

receivers:
- name: nhidongthanhpho-telegram
  webhook_configs:
  - url: 'http://10.0.0.13:9087/alert/-901133248'

- name: systems-team-telegram
  webhook_configs:
  - url: 'http://10.0.0.13:9087/alert/-815609975'

route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 10s
  repeat_interval: 1m
  receiver: systems-team-telegram
  routes:
    - match:
        app_type: Nhi Đồng Thành Phố
        instance: 10.0.2.38:9100
        category: memory
      receiver: nhidongthanhpho-telegram
      group_wait: 2s

# Sử dụng route để include các cấu hình alert khác
routes:
  - receiver: systems-team-telegram
    group_by: ['instance']
    routes:
      - include: 'include/*.yml'
