global:
  resolve_timeout: 1m

receivers:
- name: ivirse-telegram
  webhook_configs:
  - url: 'http://10.0.0.14:9088/alert/-856704110'

- name: System-Team
  webhook_configs:
  - url: 'http://10.0.0.14:9088/alert/-856704110'

- name: isofh-server
  webhook_configs:
  - url: 'http://10.0.0.14:9088/alert/-983667254'

route:
  continue: false
  group_by: ['instance']
  group_interval: 30s
  group_wait: 10s
  repeat_interval: 30s
  receiver: System-Team
  routes:

  ################### STATUS #################
    #  LOCAL isofh 
    - match:
        category: container-status
        container_name: searching-service
        app_type: Server Test
      receiver: isofh-server
      group_wait: 3s

    - match:
        category: container-status
        container_name: golang-app
        app_type: Server Test
      receiver: isofh-server
      group_wait: 3s  

    - match:
        category: container-status
        container_name: golang-app
        app_type: Server Test
      receiver: isofh-server
      group_wait: 3s  
  
  #  IVIRSE
    - match:
        category: container-status
        container_name: isofh_caserver_1
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 2s

    - match:
        category: container-status
        container_name: cadvisor
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 3s



  ################### RAM #################
    #  LOCAL isofh 
    - match:
        category: container-memory
        container_name: searching-service
        app_type: Server Test
      receiver: isofh-server
      group_wait: 3s

    - match:
        category: container-memory
        container_name: golang-app
        app_type: Server Test
      receiver: isofh-server
      group_wait: 3s  

    - match:
        category: container-memory
        container_name: golang-app
        app_type: Server Test
      receiver: isofh-server
      group_wait: 3s  



  #  IVIRSE
    - match:
        category: container-memory
        container_name: isofh_postgres_1
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 3s

    - match:
        category: container-memory
        container_name: isofh_caserver_1
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 3s















templates:
- '/etc/alertmanager/template/template.tmpl'
