global:
  resolve_timeout: 1m

receivers:
- name: BV-BachMai-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-932865047'
  
route:
  continue: false
  group_by: ['job','severity']
  group_interval: 1m
  group_wait: 30s
  receiver: BV-BachMai-telegram
  repeat_interval: 1m
  routes:
  - receiver: BV-BachMai-telegram