global:
  resolve_timeout: 5m

receivers:
- name: ivirse-telegram
  webhook_configs:
  - url: 'http://10.0.0.14:9088/alert/-856704110'

- name: System-Team
  webhook_configs:
  - url: 'http://10.0.0.14:9088/alert/-856704110'

route:
  continue: false
  group_by: ['instance']
  group_interval: 30s
  group_wait: 10s
  repeat_interval: 10m
  receiver: System-Team
  routes:

  ################### STATUS #################
  #  IVIRSE
    - match:
        category: container-status
        container_name: isofh_caserver_1
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 2s

    - match:
        category: container-status
        container_name: cadvisor
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 3s

    - match:
        category: container-memory
        container_name: cadvisor
        app_type: IVIRSE
      receiver: ivirse-telegram
      group_wait: 3s

















templates:
- '/etc/alertmanager/template/template.tmpl'
