global:
  resolve_timeout: 1m

receivers:
- name: System-Team
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 6612849064:AAGR795EyHyn278L0WRLeqiTyBuCWRRhjMg
    chat_id: -998222571
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""

- name: BV-BachMai-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-932865047'


- name: Mediplus-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'

- name: jenkins-tuan-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'

route:
  continue: false
  group_by: ['job','severity']
  group_interval: 1m
  group_wait: 30s
  repeat_interval: 1m
  receiver: System-Team
  routes:
  - match_re: 
     app_type: (bachmai|mediplus|jenkins-tuan)
    receiver: System-Team 
    routes:
    # Bạch Mai group
    # - match:
    #     app_type: bachmai
    #   receiver: BV-BachMai-telegram
    # # Mediplus group
    # - match:
    #     app_type: mediplus
    #   receiver: Mediplus-telegram
    # Jenkins group
    - match:
        app_type: jenkins-tuan
      receiver: jenkins-tuan-telegram