groups:
- name: Container

# 192.168.10.231
  rules:

  - alert: Container Status his-frontend-pk40-production
    expr: container_state_status{status="exited",name=~"his-frontend-pk40-production",instance='192.168.10.231:19092'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: his-frontend-pk40-production
      app_type: Phòng Khám 40
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       Container bị EXITED

  - alert: Container Memory his-frontend-pk40-production
    expr: (container_memory_working_set_bytes{job='pk40', name='his-frontend-pk40-production'}) / (container_spec_memory_limit_bytes{job="pk40", name='his-frontend-pk40-production', instance='192.168.10.231:9092'}) * 100 > 0
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Phòng Khám 40
      category: container-memory    
      container_name: his-frontend-pk40-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **his-frontend-pk40-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU his-frontend-pk40-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='pk40',name='his-frontend-pk40-production',instance='192.168.10.231:9092' }[1m])) BY (instance, name) * 100) >= 0
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Phòng Khám 40
      category: container-cpu    
      container_name: his-frontend-pk40-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%


  - alert: Container Status project-nodejs-visualize-pk40-production
    expr: container_state_status{status="exited",name=~"project-nodejs-visualize-pk40-production",instance='192.168.10.231:19092'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: project-nodejs-visualize-pk40-production
      app_type: Phòng Khám 40
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       Container bị EXITED

  - alert: Container Memory project-nodejs-visualize-pk40-production
    expr: (container_memory_working_set_bytes{job='pk40', name='project-nodejs-visualize-pk40-production'}) / (container_spec_memory_limit_bytes{job="pk40", name='project-nodejs-visualize-pk40-production', instance='192.168.10.231:9092'}) * 100 > 0
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Phòng Khám 40
      category: container-memory    
      container_name: project-nodejs-visualize-pk40-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **project-nodejs-visualize-pk40-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU project-nodejs-visualize-pk40-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='pk40',name='project-nodejs-visualize-pk40-production',instance='192.168.10.231:9092' }[1m])) BY (instance, name) * 100) >= 0
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Phòng Khám 40
      category: container-cpu    
      container_name: project-nodejs-visualize-pk40-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%