version: "3.8"

services:
  # Alert Manager
  alertmanager:
    image: nguyenngochuy/alertmanager-vip
    container_name: sys-isofh-alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"