version: "3.8"

services:
  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: sys-isofh-prometheus
    restart: always
    user: "root"
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./data-prometheus-grafana/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.config.file=/auth-web.yml"
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
  # Alert Manager
  alertmanager:
    image: prom/alertmanager
    container_name: sys-isofh-alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      - "--web.config.file=/config/auth-web.yml"
  # Grafana
  grafana:
    image: grafana/grafana
    container_name: sys-isofh-grafana
    user: "root"
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - ./data-prometheus-grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus
# Bot Alert
