version: "3.8"

services:
  # Prometheus
  prometheus:
    image: nguyenngochuy/prometheus-vip
    container_name: sys-isofh-prometheus
    restart: always
    user: "root"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus:/etc/prometheus/
      - ./data-prometheus-grafana/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.config.file=/etc/prometheus/auth-web.yml"
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
  # Alert Manager
  alertmanager:
    image: nguyenngochuy/alertmanage-vip
    container_name: sys-isofh-alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      - "--web.config.file=/etc/alertmanager/config/auth-web.yml"
  # Grafana
  grafana:
    image: nguyenngochuy/grafana-vip
    container_name: sys-isofh-grafana
    user: "root"
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data-prometheus-grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus
# Bot Alert Physical
  prometheus-bot:
    container_name: sys-isofh-vipbot-physical
    image: bachdangtuan/prom-golang-bot:latest

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telegrambot/:/etc/telegrambot/
      - ./telegrambot/config.yaml:/config.yaml  
    ports:
      - 9087:9087
    restart: always

# Bot Alert Physical
  prometheus-bot-container:
    container_name: sys-isofh-vipbot-container
    image: bachdangtuan/prom-golang-bot:latest

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telegrambot-container/:/etc/telegrambot/
      - ./telegrambot-container/config.yaml:/config.yaml  
    ports:
      - 9088:9087
    restart: always

# Bot Alert Physical
  prometheus-bot-kubenetes:
    container_name: sys-isofh-vipbot-k8s
    image: bachdangtuan/prom-golang-bot:latest

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telegrambot-kubenetes/:/etc/telegrambot/
      - ./telegrambot-kubenetes/config.yaml:/config.yaml  
    ports:
      - 9089:9087
    restart: always