groups:
  - alert: Container Memory
    expr: container_memory_usage_bytes{pod='api-manager-6fffb4df6c-4qshx',instance="192.168.140.18:32645"} 
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Demo
      category: container-memory    
      container_name: golang-app
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        Container name: {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='golang-app',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 

