groups:
- name: Container
  rules:
  - alert: Container Tắt
    expr: container_state_status{status='exited',name='golang-app'} == 1
    for: 10s
    labels:
      severity: critical
      category: container
      container_name: golang-app
      app_type: Server Demo
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  ) {{ $labels.name }}
      description: |
       Container name:{{ $labels.name }}
       A container has disappeared
