groups:
- name: Container
  rules:
  - alert: Container Status isofh_caserver_1
    expr: container_state_status{status="exited",name=~"isofh_caserver_1"}
    for: 10s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: isofh_caserver_1
      app_type: IVIRSE
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  )
      description: |
       Container name:{{ $labels.name }}
       A container has disappeared

  - alert: Container Status cAdvisor isofh_caserver_1
    expr: container_state_status{status="exited",name=~"cadvisor"}
    for: 10s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: cadvisor
      app_type: IVIRSE
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  )
      description: |
       Container name:{{ $labels.name }}
       A container has disappeared

  - alert: Container Memory isofh_caserver_1
    expr: container_memory_usage_bytes{name="isofh_caserver_1",instance="103.9.211.120:19092"} 
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: isofh_caserver_1
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        Container name: {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='isofh_caserver_1',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 