groups:
- name: Container


  rules:
  - alert: Container Status 
    expr: container_state_status{status="exited",name=~"isofh_caserver_1"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: isofh_caserver_1
      app_type: IVIRSE
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       Container bị EXITED

  - alert: Container Status 
    expr: container_state_status{status="exited",name=~"cadvisor"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: cadvisor
      app_type: IVIRSE
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       Container bị EXITED

  # - alert: Container Status 
  #   expr: container_state_status{status="exited",name=~"isofh_migrate_1"} == 1
  #   for: 1s
  #   labels:
  #     severity: khẩn cấp
  #     category: container-status
  #     container_name: isofh_migrate_1
  #     app_type: IVIRSE
  #   annotations:
  #     summary: Container exited
  #     description: |

  #      CONTAINER NAME:-  {{ $labels.name }}

  #      Container bị EXITED



################################################  
################## RAM #########################  
################################################  

  - alert: Container Memory
    expr: container_memory_usage_bytes{name="isofh_migrate_1",instance="103.9.211.120:9092"} > 100000000
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: isofh_migrate_1
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME:-  {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='isofh_migrate_1',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 


  - alert: Container Memory
    expr: container_memory_usage_bytes{name="isofh_caserver_1",instance="103.9.211.120:9092"} > 100000000
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: isofh_caserver_1
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME:-  {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='isofh_caserver_1',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 

  - alert: Container Memory
    expr: container_memory_usage_bytes{name="isofh_postgres_1",instance="103.9.211.120:9092"} > 100000000
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: isofh_postgres_1
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME:-  {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='isofh_postgres_1',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 