groups:
- name: Container
  rules:

  - alert: Container Status his-ndtp-production
    expr: container_state_status{status="exited",name=~"his-ndtp-production",instance='10.0.2.41:19092'} == 0
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: his-ndtp-production
      app_type: Nhi Đồng Thành Phố
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       Container bị EXITED

  - alert: Container Memory his-ndtp-production
    expr: (container_memory_working_set_bytes{job='ndtp', name='his-ndtp-production'}) / (container_spec_memory_limit_bytes{job="ndtp", name='his-ndtp-production', instance='10.0.2.41:9092'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Nhi Đồng Thành Phố
      category: container-memory    
      container_name: his-ndtp-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **his-ndtp-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU his-ndtp-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='ndtp',name='his-ndtp-production',instance='10.0.2.41:9092' }[1m])) BY (instance, name) * 100) > 500
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Nhi Đồng Thành Phố
      category: container-cpu    
      container_name: his-ndtp-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%


# rate(container_memory_usage_bytes{name=~".+",job="$job",instance=~"$node:$port"}[2m])
# sum(rate(container_cpu_usage_seconds_total{name=~".+",job=~"$job",image!="",instance=~"$node:$port"}[$interval])) by (name) * 100