# routes/server1.yml
route:
  group_by: ['instance']
  group_wait: 10s
  repeat_interval: 1h
  receiver: server1-receiver

receivers:
  - name: server1-receiver
    webhook_configs:
      - url: 'http://10.0.0.232:9087/alert/-932865047'
