    - match:
        app_type: jenkins-tuan
        instance: 10.0.0.211:19100
        category: memory  
      receiver: jenkins-tuan-telegram
      group_wait: 2s
    - match:
        app_type: jenkins-tuan
        instance: 10.0.0.210:9100
        category: memory  
      receiver: jenkins-tuan-telegram
      group_wait: 4s
# CPU
    - match:
        app_type: jenkins-tuan
        instance: 10.0.0.210:9100
        category: cpu  
      receiver: jenkins-tuan-telegram
      group_wait: 1s
    - match:
        app_type: jenkins-tuan
        instance: 10.0.0.211:19100
        category: cpu  
      receiver: jenkins-tuan-telegram
      group_wait: 1s
# DISK
    - match:
        app_type: jenkins-tuan
        instance: 10.0.0.210:9100
        category: disk  
      receiver: jenkins-tuan-telegram
      group_wait: 1s
    - match:
        app_type: jenkins-tuan
        instance: 10.0.0.211:19100
        category: disk  
      receiver: jenkins-tuan-telegram
      group_wait: 1s