groups:
  - name: jenkinsTuan-rules
    rules:
      - alert: Cảnh báo RAM
        expr: (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~".+"} - node_memory_MemFree_bytes{job="jenkins-tuan", instance=~".+"}) / (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~".+"}) * 100 >= 90
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: jenkins-tuan
          category: memory
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM Server > 90%"
          description: |
            RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% 
                 * Ram sử dụng (ram dùng + ram cache/buffer)
            Thông tin cụ thể:

                 * TOTAL RAM:  {{ query (printf "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'%s'}" $labels.instance) | first | value | humanize }}

                 * Ram sử dụng:  {{ query (printf "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'%s'} - node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'%s'}" $labels.instance $labels.instance ) | first | value | humanize }}
                  
                 * Ram còn lại:  {{ query (printf "node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'%s'}" $labels.instance) | first | value | humanize }}

