groups:
  - name: jenkinsTuan-rules
    rules:

    - alert: Node Exporter Down
      expr: up{job="jenkins-tuan",instance="10.0.0.211:19100"} == 0
      for: 1m
      labels:
        severity: critical
        app_type: jenkins-tuan
        category: server
      annotations:
        summary: "Node Exporter in Demo server is down"
        description: "Node Exporter is down for more than 2 minutes"

    - record: job:node_memory_Mem_bytes:available
      expr: (node_memory_MemFree_bytes{job="Mediplus"} / node_memory_MemTotal_bytes{job="Mediplus"}) * 100  

  # Phần trăm ram sử dụng bằng 100 - (ram còn lại / tổng ram ) *100
    - alert: Mức độ ram sử dụng
      expr: (node_memory_MemTotal_bytes{job="jenkins-tuan"} - node_memory_MemFree_bytes{job="jenkins-tuan"} - node_memory_Buffers_bytes{job="jenkins-tuan"} - node_memory_Cached_bytes{job="jenkins-tuan"}) / (node_memory_MemTotal_bytes{job="jenkins-tuan"}) * 100 >= 70
      for: 1m
      labels:
        severity: warning
        app_type: jenkins-tuan
        category: memory
      annotations:
        summary: "RAM máy chủ vượt quá 70%"
        description: |
          Node memory for instance has reached {{ $value }}%.
          Additional information:
          * Free memory: {{ humanizeBytes (query "node_memory_MemFree_bytes{job=\"jenkins-tuan\"}" | first) }}
