groups:
  - name: jenkinsTuan-rules
    rules:
      # Ram Rules
      - alert: Cảnh báo RAM
        expr: (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~".+"} - node_memory_MemFree_bytes{job="jenkins-tuan", instance=~".+"}) / (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~".+"}) * 100 >= 1
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: jenkins-tuan
          category: memory
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM Server > 90%"
          description: |
            RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% / 100%
                 * Ram sử dụng (ram dùng + ram cache/buffer)
            Thông tin cụ thể:

                 * TOTAL RAM:  {{ query (printf "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'%s'}" $labels.instance) | first | value | humanize }}

                 * Ram sử dụng:  {{ query (printf "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'%s'} - node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'%s'}" $labels.instance $labels.instance ) | first | value | humanize }}
                  
                 * Ram còn lại:  {{ query (printf "node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'%s'}" $labels.instance) | first | value | humanize }}

      # CPU Rules
      - alert: CPU Tăng cao
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{job="jenkins-tuan", instance=~".+",mode="idle"}[1m])) * 100) > 0.0001
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: jenkins-tuan
          category: cpu
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "CPU Server > 90%"
          description: | 
            CPU máy chủ sử dụng đạt tới  {{ printf "%.2f" $value }}% / 100%

      # Disk Rules
      - alert: Dung Lượng nhỏ hơn 10%
        expr: ((node_filesystem_free_bytes{instance=~".+",job="jenkins-tuan",mountpoint="/"}) / (node_filesystem_size_bytes{instance=~".+",job="jenkins-tuan",mountpoint="/"})) * 100 > 1
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: jenkins-tuan
          category: disk
        annotations:
          summary: "Dung lượng ổ cứng server nhỏ hơn 10%"
          description: "Node disk is going to full (< 10% left)\n  Current free disk space is {{ $value }}"