# groups:
#   - name: jenkinsTuan-rules
#     rules:

#     - alert: Node Exporter Down
#       expr: up{job="jenkins-tuan",instance="10.0.0.211:19100"} == 0
#       for: 1m
#       labels:
#         severity: critical
#         app_type: jenkins-tuan
#         category: server
#       annotations:
#         summary: "Node Exporter in Demo server is down"
#         description: "Node Exporter is down for more than 2 minutes"

#     - record: job:node_memory_Mem_bytes:available
#       expr: (node_memory_MemFree_bytes{job="Mediplus"} / node_memory_MemTotal_bytes{job="Mediplus"}) * 100  

#   # Phần trăm ram sử dụng bằng 100 - (ram còn lại / tổng ram ) *100
#     # - alert: Cảnh báo RAM
#     #   expr: (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~'.+'} - node_memory_MemFree_bytes{job="jenkins-tuan", instance=~'.+'} - node_memory_Buffers_bytes{job="jenkins-tuan", instance=~'.+'} - node_memory_Cached_bytes{job="jenkins-tuan", instance=~'.+'}) / (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~'.+'}) * 100 >= 1
#     #   for: 1m
#     #   labels:
#     #     severity: CẢNH BÁO
#     #     app_type: jenkins-tuan
#     #     category: memory
#     #     instance: "{{ $labels.instance }}"
#     #   annotations:
#     #     summary: "RAM Server > 70% {{ $labels.instance }}"
#     #     description: |
#     #       RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% trên instance {{ $labels.instance }}..
#     #       Thông tin cụ thể:
#     #       * Ram sử dụng: {{ query "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'.+'} - node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'.+'} - node_memory_Buffers_bytes{job='jenkins-tuan', instance=~'.+'} - node_memory_Cached_bytes{job='jenkins-tuan', instance=~'.+'}" | first | value | humanize }}
#     #       * Ram còn lại: {{ query "node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'.+'}" | first | value | humanize }}
#     #       * Tổng RAM: {{ query "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'.+'}" | first | value | humanize  }}





#     # - alert: CPU Tăng Cao
#     #   expr: 100 * (1 - (sum(rate(node_cpu_seconds_total{mode="idle", job="Mediplus"}[2m])) / sum(rate(node_cpu_seconds_total{job="Mediplus"}[2m))))) > 80
#     #   for: 1m
#     #   labels:
#     #     severity: CẢNH BÁO
#     #     app_type: mediplus
#     #     category: cpu
#     #   annotations:
#     #     summary: "CPU Tăng Cao > 80%"
#     #     description: | 
#     #       CPU đã sử dụng chiếm {{ printf "%.2f" $value }}%
#     #       Thông tin cụ thể:
#     #       * CPU sử dụng {{ printf "%.2f" $value }}%
#     #       * CPU còn lại {{ query "100 - (100 * (1 - (sum(rate(node_cpu_seconds_total{mode=\"idle\", job=\"Mediplus\"}[2m])) / sum(rate(node_cpu_seconds_total{job=\"Mediplus\"}[2m)))))" | first | value | humanize }}      
groups:
  - name: jenkinsTuan-rules
    rules:
      - alert: Cảnh báo RAM
        expr: (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~".+"} - node_memory_MemFree_bytes{job="jenkins-tuan", instance=~".+"} - node_memory_Buffers_bytes{job="jenkins-tuan", instance=~".+"} - node_memory_Cached_bytes{job="jenkins-tuan", instance=~".+"}) / (node_memory_MemTotal_bytes{job="jenkins-tuan", instance=~".+"}) * 100 >= 1
        for: 1m
        labels:
          severity: CẢNH BÁO
          app_type: jenkins-tuan
          category: memory
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM Server > 70% {{ $labels.instance }}"
          description: |
            RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% trên instance {{ $labels.instance }}..
            Thông tin cụ thể:
            * Ram sử dụng: {{ query "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'.+'} - node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'.+'} - node_memory_Buffers_bytes{job='jenkins-tuan', instance=~'.+'} - node_memory_Cached_bytes{job='jenkins-tuan', instance=~'.+'}" | first | value | humanize }}
            * Ram còn lại: {{ query "node_memory_MemFree_bytes{job='jenkins-tuan', instance=~'.+'}" | first | value | humanize }}
            * Tổng RAM: {{ query "node_memory_MemTotal_bytes{job='jenkins-tuan', instance=~'.+'}" | first | value | humanize  }}
