groups:
  - name: Nhi Đồng Thành Phố-Rules
    rules:
      # Node Down
      - alert: Node-export bị tắt
        expr:  up{job="Nhi-Dong-Thanh-Pho",instance=~".+"} == 0
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: Nhi Đồng Thành Phố
          category: server
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Node-export trên server {{ $labels.instance }} bị tắt"
          description: | 
                Vui lòng kiểm tra lại node-exporter trên server hoặc kiểm tra server có bị tắt hay không ?

      # Ram Rules
      - alert: Cảnh báo RAM
        expr: (node_memory_MemTotal_bytes{job="Nhi-Dong-Thanh-Pho", instance=~".+"} - node_memory_MemFree_bytes{job="Nhi-Dong-Thanh-Pho", instance=~".+"}) / (node_memory_MemTotal_bytes{job="Nhi-Dong-Thanh-Pho", instance=~".+"}) * 100 >= 90
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: Nhi Đồng Thành Phố
          category: memory
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM Server > 90%"
          description: |
            RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% / 100%

                 * Ram sử dụng (ram dùng + ram cache/buffer)
                 
            Thông Tin Cụ Thể:


                 * TOTAL RAM:  {{ query (printf "node_memory_MemTotal_bytes{job='Nhi-Dong-Thanh-Pho', instance=~'%s'}" $labels.instance) | first | value | humanize }}

                 * Ram sử dụng:  {{ query (printf "node_memory_MemTotal_bytes{job='Nhi-Dong-Thanh-Pho', instance=~'%s'} - node_memory_MemFree_bytes{job='Nhi-Dong-Thanh-Pho', instance=~'%s'}" $labels.instance $labels.instance ) | first | value | humanize }}
                  
                 * Ram còn lại:  {{ query (printf "node_memory_MemFree_bytes{job='Nhi-Dong-Thanh-Pho', instance=~'%s'}" $labels.instance) | first | value | humanize }}

      # CPU Rules
      - alert: CPU Tăng cao
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{job="Nhi-Dong-Thanh-Pho", instance=~".+",mode="idle"}[1m])) * 100) > 80
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: Nhi Đồng Thành Phố
          category: cpu
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "CPU Server > 90%"
          description: | 
            CPU máy chủ sử dụng đạt tới  {{ printf "%.2f" $value }}% / 100%

      # Disk Rules
      - alert: Dung lượng DISK
        expr: ((node_filesystem_free_bytes{instance=~".+",job="Nhi-Dong-Thanh-Pho",mountpoint="/"}) / (node_filesystem_size_bytes{instance=~".+",job="Nhi-Dong-Thanh-Pho",mountpoint="/"})) * 100 > 95
        for: 1m
        labels:
          severity: Rất Nguy Hiểm
          app_type: Nhi Đồng Thành Phố
          category: disk
        annotations:
          summary: "Ổ CỨNG SẮP ĐẦY"
          description: | 

              DUNG LƯỢNG Ổ CỨNG SỬ DỤNG ĐẠT
              
              {{ printf "%.2f" $value }}% / 100%

              Vào fix đi anh em !
              