groups:
  - name: Trung Tâm Tim Mạch-Rules
    rules:
      # Node Down
      - alert: Cảnh Báo Server
        expr:  up{job="Trung-Tam-Tim-Mach",instance=~".+"} == 0
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Trung-Tam-Tim-Mach
          category: server
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Server bị tắt"
          description: | 
                Vui lòng kiểm tra lại node-exporter trên server hoặc kiểm tra server có bị tắt hay không ?

      # Ram Rules
      - alert: Cảnh báo RAM
        expr: (node_memory_MemTotal_bytes{job="Trung-Tam-Tim-Mach", instance=~".+"} - node_memory_MemFree_bytes{job="Trung-Tam-Tim-Mach", instance=~".+"}) / (node_memory_MemTotal_bytes{job="Trung-Tam-Tim-Mach", instance=~".+"}) * 100 >= 90
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Trung-Tam-Tim-Mach
          category: memory
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM Server > 90%"
          description: |
            RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% / 100%
                             
            Thông Tin Cụ Thể:

                 * TOTAL RAM:  {{ query (printf "node_memory_MemTotal_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s'}" $labels.instance) | first | value | humanize }}

                 * Ram sử dụng:  {{ query (printf "node_memory_MemTotal_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s'} - node_memory_MemFree_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s'}" $labels.instance $labels.instance ) | first | value | humanize }}
                  
                 * Ram còn lại:  {{ query (printf "node_memory_MemFree_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s'}" $labels.instance) | first | value | humanize }}

      # CPU Rules
      - alert: CPU Tăng cao
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{job="Trung-Tam-Tim-Mach", instance=~".+",mode="idle"}[1m])) * 100) > 90
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Trung-Tam-Tim-Mach
          category: cpu
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "CPU Server > 90%"
          description: | 
            CPU máy chủ sử dụng đạt tới  {{ printf "%.2f" $value }}% / 100%

      # Disk Rules
      - alert: Dung lượng DISK
        expr: (100 - ((node_filesystem_free_bytes{instance=~".+",job="Trung-Tam-Tim-Mach",mountpoint=~".+"}) / (node_filesystem_size_bytes{instance=~".+",job="Trung-Tam-Tim-Mach",mountpoint=~".+"}))* 100) > 95
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Trung-Tam-Tim-Mach
          category: disk
        annotations:
          summary: "Ổ CỨNG SẮP ĐẦY"
          description: | 
          
              Dung lượng {{ $labels.device }} mount vào thư mục {{ $labels.mountpoint }} đã đạt tới {{ printf "%.2f" $value }}% / 100%

              Thông Tin Cụ Thể:

                  * TOTAL DISK:  {{ query (printf "node_filesystem_size_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s', mountpoint=~'%s'}" $labels.instance $labels.mountpoint) | first | value | humanize}}

                  * KL Đã dùng:  {{ query (printf "node_filesystem_size_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s', mountpoint=~'%s'} - node_filesystem_free_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s', mountpoint=~'%s'}" $labels.instance $labels.mountpoint $labels.instance $labels.mountpoint) | first | value | humanize}}

                  * KL Còn lại:  {{ query (printf "node_filesystem_free_bytes{job='Trung-Tam-Tim-Mach', instance=~'%s', mountpoint=~'%s'}" $labels.instance $labels.mountpoint) | first | value | humanize}}

              Vào fix đi anh em !
              
